### ISSUE TITLE
Testet it out dos not seem to work

### ISSUE THREAD

**Issue by benzon** [zfbx/FiveM-Seatbelt#1]
Well tested it out multiple times now even on a clean server, and it dos not rly react to be honest, i can drive with 120 km/t in to a wall nothing happens, even tho it should let me fly out the vehicle.

**Comment by zfbx** [comment]
A) Are you using the most recent version? there were some bugs that needed fixing and 

B) do you have `setr game_enableFlyThroughWindscreen true` in your server.cfg cause without that line this seatbelt script wont work at all

**Comment by zfbx** [comment]
going to assume you figured it out or moved to one of the other seatbelt scripts and close this :)
